#pragma once

#ifdef __cplusplus
extern "C" {
#endif

struct header;
struct obj_theme;
struct feature_type;
struct object_kind;
struct artifact_type;
struct ego_item_type;
struct randart_part_type;
struct randart_gen_type;
struct monster_blow;
struct monster_race;
struct monster_ego;
struct vault_type;
struct trap_type;
struct cave_type;
struct effect_type;
struct object_type;
struct monster_mind;
struct monster_type;
struct alloc_entry;
struct option_type;
struct owner_type;
struct store_type;
struct store_info_type;
struct store_action_type;
struct magic_type;
struct player_sex;
struct player_race;
struct player_race_mod;
struct player_spec;
struct player_class;
struct meta_class_type;
struct help_info;
struct player_type;
struct martial_arts;
struct magic_power;
struct border_type;
struct wilderness_type_info;
struct wilderness_map;
struct town_type;
struct alchemist_recipe;
struct artifact_select_flag;
struct deity_type;
struct tactic_info_type;
struct random_artifact;
struct activation;
struct music;
struct random_spell;
struct fate;
struct move_info_type;
struct rule_type;
struct dungeon_info_type;
struct inscription_info_type;
struct rune_spell;
struct flags_group;
struct power_type;
struct hook_move_in;
struct hook_get_in;
struct hook_end_turn_in;
struct hook_player_level_in;
struct hook_identify_in;
struct hook_give_in;
struct hook_eat_in;
struct hook_eat_out;
struct hook_stair_in;
struct hook_stair_out;
struct hook_new_monster_end_in;
struct quest_type;
struct random_quest;
struct monster_power;
struct tval_desc;
struct between_exit;
struct birther;
struct hist_type;
struct set_type;
struct cli_comm;
struct skill_type;
struct school_idx;
struct spell_type;
struct school_provider_list;
struct school_type;
struct school_book_type;
struct gf_name_type;
struct timer_type;
struct list_type;
struct ability_type;
struct module_meta_type;
struct module_type;
struct corruption_type;
struct mimic_duration_type;
struct mimic_form_type;

#ifdef __cplusplus
}
#endif
